version: '2.1'
services:

  web:
    restart: always
    build: .
    volumes:
      - .:/app
    command: >
      sh -c "python backend/manage.py"
    env_file:
      - .env
    depends_on:
      - postgres
    environment:
      PYTHONPATH: /app
    ports:
      - "8000:5000"

  postgres:
    user: postgres
    restart: always
    build:
      context: ./docker-entrypoint
      dockerfile: db.Dockerfile
    volumes:
      - kanalservic:/var/lib/postgresql/data/
    ports:
      - "5432:5432"

volumes:
  kanalservic:
  flask:
